export const TEMP_INDICATOR = {
  TEST_ID: {
    CONTAINER: 'TEMP_INDICATOR_CONTAINER_TEST_ID',
    GRADIENT: 'TEMP_INDICATOR_GRADIENT_TEST_ID',
    MIN: 'TEMP_INDICATOR_MIN_TEST_ID',
    MAX: 'TEMP_INDICATOR_MAX_TEST_ID',
  },
  GRADIENT: {
    START: { x: 0, y: 0 },
    END: { x: 1, y: 0 },
  },
};
