export const ITEM = {
  TEST_ID: {
    CONTAINER: 'ITEM_CONTAINER_TEST_ID',
    LABEL: 'ITEM_LABEL_TEST_ID',
    ICON_BUTTON: 'ITEM_ICON_BUTTON_TEST_ID',
    TEMP_INDICATOR: 'ITEM_TEMP_INDICATOR_TEST_ID',
  },
};
