export const STYLE = {
  DEFAULT_ALLOWED_PROPERTIES: [
    'zIndex',
    'position',
    'top',
    'right',
    'bottom',
    'left',
    'margin',
    'marginTop',
    'marginBottom',
    'marginLeft',
    'marginRight',
    'marginVertical',
    'marginHorizontal',
    'marginStart',
    'marginEnd',
    'alignSelf',
    'opacity',
    'fontWeight',
    'textAlign',
    'textTransform',
  ],
};
