export const ICON_BUTTON = {
  TEST_ID: {
    CONTAINER: 'ICON_BUTTON_CONTAINER_TEST_ID',
    ACTIVITY_INDICATOR: 'ICON_BUTTON_ACTIVITY_INDICATOR_TEST_ID',
    ICON: 'ICON_BUTTON_ICON_TEST_ID',
  },
};
